version: '3.8'

services:
  # Backend service (FastAPI)
  backend:
    build: ./backend
    container_name: cs-department-backend
    ports:
      - "8000:8000"
    environment:
      - FRONTEND_URL=http://localhost:3000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - cs-department-network
    restart: unless-stopped

  # Frontend service (React)
  frontend:
    build: ./frontend
    container_name: cs-department-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - cs-department-network
    restart: unless-stopped

networks:
  cs-department-network:
    driver: bridge

volumes:
  backend_data: